# Generated by Django 5.0.2 on 2024-12-20 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Obligatorio', max_length=50)),
                ('descripcion', models.TextField()),
                ('metodo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_cooking.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_ingredientes', to='daily_cooking.receta')),
            ],
        ),
    ]
