# Generated by Django 5.0.2 on 2024-12-21 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_cooking', '0002_restriccionesusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientesusuario',
            name='nombre_ingrediente',
        ),
        migrations.AddField(
            model_name='ingredientesusuario',
            name='ingredientes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ingredientesusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
